### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZippingBoat9588** [UnknownNull/SpaceRemover#3]
![Screenshot_20220714-191930.png](https://user-images.githubusercontent.com/104681534/179050297-8240d5cb-e8bc-430b-a56a-1c5dd1dbcec4.png)
@UnknownNull ITS Crash If i try to Join please fix it

**Comment by UnknownNull** [comment]
Remove player folder and try again @ZippingBoat9588

**Comment by ZippingBoat9588** [comment]
But the inventory is emty then and all is gone

**Comment by ZippingBoat9588** [comment]
> Remove player folder and try again @ZippingBoat9588 

So If i delete the Player folder will it delete the inventory of the Players? @UnknownNull

**Comment by UnknownNull** [comment]
Yes.  Or you can delete the player in which space is used
@ZippingBoat9588

**Comment by ZippingBoat9588** [comment]
> Yes.  Or you can delete the player in which space is used
> @ZippingBoat9588 

So i have to delete all Players with spaces Amt then it will Work?

**Comment by ZippingBoat9588** [comment]
@UnknownNull so i delete all Players in Player folder but its still Crash why?![Screenshot_20220714-213527.png](https://user-images.githubusercontent.com/104681534/179068686-e38fa211-6316-421b-8fec-6ccf671eb9b8.png)

**Comment by UnknownNull** [comment]
This will be fixed in the next update.  Thank you for your report♡

**Comment by ZippingBoat9588** [comment]
> This will be fixed in the next update.  Thank you for your report♡

No Problem can you remind me If Update is Out?

**Comment by UnknownNull** [comment]
@ZippingBoat9588 this fixed
Preview: https://github.com/UnknownNull/SpaceRemover/blob/main/Preview.gif

**Comment by ZippingBoat9588** [comment]
@UnknownNull Not fixt they have spaces

**Comment by ZippingBoat9588** [comment]
![Screenshot_20220715-122443.png](https://user-images.githubusercontent.com/104681534/179205466-943f69c5-5779-49e9-a781-a53b0253585b.png)

**Comment by ZippingBoat9588** [comment]
I use latest Dev build dev19

**Comment by UnknownNull** [comment]
@ZippingBoat9588 remove mr coks gamer.dat and remove other plaugins space remover and run server

**Comment by ZippingBoat9588** [comment]
> @ZippingBoat9588 remove mr coks gamer.dat and remove other plaugins space remover and run server

I did this but ITS Not work this Player was me and wars never Connect before i dele His Play dat and Not work

**Comment by UnknownNull** [comment]
whats version pocketmine?

**Comment by ZippingBoat9588** [comment]
Damm i am so sorry i dient know i have to load it with Dev tools it Work perfectly thank you pls hold the Plugin aktiv and updated

**Comment by UnknownNull** [comment]
I'm glad you succeeded.✅
